spring:
  #MYSQL 설정정보
  datasource:
    url: jdbc:mysql://localhost:3306/elevator?autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: elevator
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
